
### PUT
PUT http://localhost:3000/api/menu/86
Content-Type: application/json

{
    "hotdog_name": "Classic Hotdog",
    "base_price": "15.00"
}


### post /products
POST http://127.0.0.1:3000/api/menu
Content-Type: application/json

{
  "hotdog_name": "Classic Hotdog",
  "base_price": 5.99,
  "topping_ids": [1, 2, 3]
}

###Get
GET http://localhost:3000/api/menu
